apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jumper.fullname" . }}-config
  labels:
    {{- include "jumper.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configFiles }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
