{{- if and .Values.vncAuth.enabled .Values.vncAuth.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jumper.fullname" . }}-vnc-auth
  labels:
    {{- include "jumper.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.vncAuth.username | b64enc | quote }}
  password: {{ .Values.vncAuth.password | b64enc | quote }}
{{- end -}}
